// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gsst.Services;

#nullable disable

namespace Petrol.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602211230_AdminPhone")]
    partial class AdminPhone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PumpTank", b =>
                {
                    b.Property<int>("ConnectedPumpsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedTanksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectedPumpsId", "ConnectedTanksId");

                    b.HasIndex("ConnectedTanksId");

                    b.ToTable("PumpTank");
                });

            modelBuilder.Entity("gsst.Model.BonusCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BonusBalance")
                        .HasColumnType("REAL");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BonusCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1234",
                            BonusBalance = 100.0,
                            ClientName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "5678",
                            BonusBalance = 200.0,
                            ClientName = "Jane Smith"
                        });
                });

            modelBuilder.Entity("gsst.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "A-95",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "A-92",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Diesel",
                            Price = 6.0
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Gas",
                            Price = 3.0
                        });
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GasStationId");

                    b.ToTable("Pumps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GasStationId = 1,
                            Name = "Pump 1",
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            GasStationId = 1,
                            Name = "Pump 2",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            GasStationId = 2,
                            Name = "Pump 3",
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            GasStationId = 2,
                            Name = "Pump 4",
                            Status = 2
                        });
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GasStationId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 1,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 1,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 2,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 2,
                            Volume = 5000.0
                        });
                });

            modelBuilder.Entity("gsst.Model.GasStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GasStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Złota 59, 00-120 Warszawa",
                            Latitude = 52.229999999999997,
                            Longitude = 21.002400000000002,
                            Name = "Shell Warszawa Centrum"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Targowa 12, 03-736 Warszawa",
                            Latitude = 52.251399999999997,
                            Longitude = 21.041599999999999,
                            Name = "Shell Warszawa Praga"
                        });
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccruedBonuses")
                        .HasColumnType("REAL");

                    b.Property<int?>("BonusCardId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BonusSpent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("gsst.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("gsst.Model.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GasStationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Михайло Стадніков",
                            Password = "password",
                            PhoneNumber = "+48000000001",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Олексій Романенко",
                            Password = "cashier",
                            Role = "Cashier",
                            Username = "cashier"
                        });
                });

            modelBuilder.Entity("gsst.Model.Fuel", b =>
                {
                    b.HasBaseType("gsst.Model.Product");

                    b.Property<int>("PumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("PumpId");

                    b.HasIndex("TypeId");

                    b.HasDiscriminator().HasValue("Fuel");
                });

            modelBuilder.Entity("gsst.Model.Good", b =>
                {
                    b.HasBaseType("gsst.Model.Product");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasDiscriminator().HasValue("Good");
                });

            modelBuilder.Entity("PumpTank", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.Pump", null)
                        .WithMany()
                        .HasForeignKey("ConnectedPumpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.FuelStuff.Tank", null)
                        .WithMany()
                        .HasForeignKey("ConnectedTanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gsst.Model.BonusCard", b =>
                {
                    b.HasOne("gsst.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gsst.Model.CartItem", b =>
                {
                    b.HasOne("gsst.Model.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("gsst.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Pump", b =>
                {
                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Pumps")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Tank", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Tanks")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.HasOne("gsst.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gsst.Model.User.User", b =>
                {
                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Managers")
                        .HasForeignKey("GasStationId");
                });

            modelBuilder.Entity("gsst.Model.Fuel", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.FuelStuff.FuelType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pump");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("gsst.Model.GasStation", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Pumps");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
