// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gsst.Services;

#nullable disable

namespace Petrol.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604014621_PaymentMethodFix")]
    partial class PaymentMethodFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PumpTank", b =>
                {
                    b.Property<int>("ConnectedPumpsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedTanksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectedPumpsId", "ConnectedTanksId");

                    b.HasIndex("ConnectedTanksId");

                    b.ToTable("PumpTank");

                    b.HasData(
                        new
                        {
                            ConnectedPumpsId = 1,
                            ConnectedTanksId = 1
                        },
                        new
                        {
                            ConnectedPumpsId = 1,
                            ConnectedTanksId = 2
                        },
                        new
                        {
                            ConnectedPumpsId = 2,
                            ConnectedTanksId = 1
                        },
                        new
                        {
                            ConnectedPumpsId = 3,
                            ConnectedTanksId = 3
                        },
                        new
                        {
                            ConnectedPumpsId = 3,
                            ConnectedTanksId = 4
                        },
                        new
                        {
                            ConnectedPumpsId = 4,
                            ConnectedTanksId = 4
                        },
                        new
                        {
                            ConnectedPumpsId = 5,
                            ConnectedTanksId = 5
                        },
                        new
                        {
                            ConnectedPumpsId = 5,
                            ConnectedTanksId = 6
                        },
                        new
                        {
                            ConnectedPumpsId = 5,
                            ConnectedTanksId = 7
                        },
                        new
                        {
                            ConnectedPumpsId = 5,
                            ConnectedTanksId = 8
                        },
                        new
                        {
                            ConnectedPumpsId = 6,
                            ConnectedTanksId = 5
                        },
                        new
                        {
                            ConnectedPumpsId = 6,
                            ConnectedTanksId = 6
                        },
                        new
                        {
                            ConnectedPumpsId = 6,
                            ConnectedTanksId = 7
                        },
                        new
                        {
                            ConnectedPumpsId = 6,
                            ConnectedTanksId = 8
                        },
                        new
                        {
                            ConnectedPumpsId = 7,
                            ConnectedTanksId = 5
                        },
                        new
                        {
                            ConnectedPumpsId = 7,
                            ConnectedTanksId = 6
                        },
                        new
                        {
                            ConnectedPumpsId = 7,
                            ConnectedTanksId = 7
                        },
                        new
                        {
                            ConnectedPumpsId = 7,
                            ConnectedTanksId = 8
                        },
                        new
                        {
                            ConnectedPumpsId = 8,
                            ConnectedTanksId = 5
                        },
                        new
                        {
                            ConnectedPumpsId = 8,
                            ConnectedTanksId = 6
                        },
                        new
                        {
                            ConnectedPumpsId = 8,
                            ConnectedTanksId = 7
                        },
                        new
                        {
                            ConnectedPumpsId = 8,
                            ConnectedTanksId = 8
                        },
                        new
                        {
                            ConnectedPumpsId = 9,
                            ConnectedTanksId = 9
                        },
                        new
                        {
                            ConnectedPumpsId = 9,
                            ConnectedTanksId = 10
                        },
                        new
                        {
                            ConnectedPumpsId = 10,
                            ConnectedTanksId = 9
                        },
                        new
                        {
                            ConnectedPumpsId = 10,
                            ConnectedTanksId = 10
                        },
                        new
                        {
                            ConnectedPumpsId = 11,
                            ConnectedTanksId = 9
                        },
                        new
                        {
                            ConnectedPumpsId = 11,
                            ConnectedTanksId = 10
                        },
                        new
                        {
                            ConnectedPumpsId = 12,
                            ConnectedTanksId = 9
                        },
                        new
                        {
                            ConnectedPumpsId = 12,
                            ConnectedTanksId = 10
                        },
                        new
                        {
                            ConnectedPumpsId = 13,
                            ConnectedTanksId = 11
                        },
                        new
                        {
                            ConnectedPumpsId = 13,
                            ConnectedTanksId = 12
                        },
                        new
                        {
                            ConnectedPumpsId = 13,
                            ConnectedTanksId = 13
                        },
                        new
                        {
                            ConnectedPumpsId = 14,
                            ConnectedTanksId = 11
                        },
                        new
                        {
                            ConnectedPumpsId = 14,
                            ConnectedTanksId = 12
                        },
                        new
                        {
                            ConnectedPumpsId = 14,
                            ConnectedTanksId = 13
                        },
                        new
                        {
                            ConnectedPumpsId = 15,
                            ConnectedTanksId = 11
                        },
                        new
                        {
                            ConnectedPumpsId = 15,
                            ConnectedTanksId = 12
                        },
                        new
                        {
                            ConnectedPumpsId = 15,
                            ConnectedTanksId = 13
                        },
                        new
                        {
                            ConnectedPumpsId = 16,
                            ConnectedTanksId = 11
                        },
                        new
                        {
                            ConnectedPumpsId = 16,
                            ConnectedTanksId = 12
                        },
                        new
                        {
                            ConnectedPumpsId = 16,
                            ConnectedTanksId = 13
                        },
                        new
                        {
                            ConnectedPumpsId = 17,
                            ConnectedTanksId = 14
                        },
                        new
                        {
                            ConnectedPumpsId = 17,
                            ConnectedTanksId = 15
                        },
                        new
                        {
                            ConnectedPumpsId = 17,
                            ConnectedTanksId = 16
                        },
                        new
                        {
                            ConnectedPumpsId = 17,
                            ConnectedTanksId = 17
                        },
                        new
                        {
                            ConnectedPumpsId = 18,
                            ConnectedTanksId = 14
                        },
                        new
                        {
                            ConnectedPumpsId = 18,
                            ConnectedTanksId = 15
                        },
                        new
                        {
                            ConnectedPumpsId = 18,
                            ConnectedTanksId = 16
                        },
                        new
                        {
                            ConnectedPumpsId = 18,
                            ConnectedTanksId = 17
                        },
                        new
                        {
                            ConnectedPumpsId = 19,
                            ConnectedTanksId = 14
                        },
                        new
                        {
                            ConnectedPumpsId = 19,
                            ConnectedTanksId = 15
                        },
                        new
                        {
                            ConnectedPumpsId = 19,
                            ConnectedTanksId = 16
                        },
                        new
                        {
                            ConnectedPumpsId = 19,
                            ConnectedTanksId = 17
                        },
                        new
                        {
                            ConnectedPumpsId = 20,
                            ConnectedTanksId = 14
                        },
                        new
                        {
                            ConnectedPumpsId = 20,
                            ConnectedTanksId = 15
                        },
                        new
                        {
                            ConnectedPumpsId = 20,
                            ConnectedTanksId = 16
                        },
                        new
                        {
                            ConnectedPumpsId = 20,
                            ConnectedTanksId = 17
                        },
                        new
                        {
                            ConnectedPumpsId = 21,
                            ConnectedTanksId = 18
                        },
                        new
                        {
                            ConnectedPumpsId = 21,
                            ConnectedTanksId = 19
                        },
                        new
                        {
                            ConnectedPumpsId = 22,
                            ConnectedTanksId = 18
                        },
                        new
                        {
                            ConnectedPumpsId = 22,
                            ConnectedTanksId = 19
                        },
                        new
                        {
                            ConnectedPumpsId = 23,
                            ConnectedTanksId = 18
                        },
                        new
                        {
                            ConnectedPumpsId = 23,
                            ConnectedTanksId = 19
                        },
                        new
                        {
                            ConnectedPumpsId = 24,
                            ConnectedTanksId = 18
                        },
                        new
                        {
                            ConnectedPumpsId = 24,
                            ConnectedTanksId = 19
                        },
                        new
                        {
                            ConnectedPumpsId = 25,
                            ConnectedTanksId = 20
                        },
                        new
                        {
                            ConnectedPumpsId = 26,
                            ConnectedTanksId = 20
                        },
                        new
                        {
                            ConnectedPumpsId = 27,
                            ConnectedTanksId = 20
                        },
                        new
                        {
                            ConnectedPumpsId = 28,
                            ConnectedTanksId = 20
                        },
                        new
                        {
                            ConnectedPumpsId = 29,
                            ConnectedTanksId = 21
                        },
                        new
                        {
                            ConnectedPumpsId = 29,
                            ConnectedTanksId = 22
                        },
                        new
                        {
                            ConnectedPumpsId = 29,
                            ConnectedTanksId = 23
                        },
                        new
                        {
                            ConnectedPumpsId = 29,
                            ConnectedTanksId = 24
                        },
                        new
                        {
                            ConnectedPumpsId = 30,
                            ConnectedTanksId = 21
                        },
                        new
                        {
                            ConnectedPumpsId = 30,
                            ConnectedTanksId = 22
                        },
                        new
                        {
                            ConnectedPumpsId = 30,
                            ConnectedTanksId = 23
                        },
                        new
                        {
                            ConnectedPumpsId = 30,
                            ConnectedTanksId = 24
                        },
                        new
                        {
                            ConnectedPumpsId = 31,
                            ConnectedTanksId = 21
                        },
                        new
                        {
                            ConnectedPumpsId = 31,
                            ConnectedTanksId = 22
                        },
                        new
                        {
                            ConnectedPumpsId = 31,
                            ConnectedTanksId = 23
                        },
                        new
                        {
                            ConnectedPumpsId = 31,
                            ConnectedTanksId = 24
                        },
                        new
                        {
                            ConnectedPumpsId = 32,
                            ConnectedTanksId = 21
                        },
                        new
                        {
                            ConnectedPumpsId = 32,
                            ConnectedTanksId = 22
                        },
                        new
                        {
                            ConnectedPumpsId = 32,
                            ConnectedTanksId = 23
                        },
                        new
                        {
                            ConnectedPumpsId = 32,
                            ConnectedTanksId = 24
                        },
                        new
                        {
                            ConnectedPumpsId = 33,
                            ConnectedTanksId = 25
                        },
                        new
                        {
                            ConnectedPumpsId = 33,
                            ConnectedTanksId = 26
                        },
                        new
                        {
                            ConnectedPumpsId = 33,
                            ConnectedTanksId = 27
                        },
                        new
                        {
                            ConnectedPumpsId = 34,
                            ConnectedTanksId = 25
                        },
                        new
                        {
                            ConnectedPumpsId = 34,
                            ConnectedTanksId = 26
                        },
                        new
                        {
                            ConnectedPumpsId = 34,
                            ConnectedTanksId = 27
                        },
                        new
                        {
                            ConnectedPumpsId = 35,
                            ConnectedTanksId = 25
                        },
                        new
                        {
                            ConnectedPumpsId = 35,
                            ConnectedTanksId = 26
                        },
                        new
                        {
                            ConnectedPumpsId = 35,
                            ConnectedTanksId = 27
                        },
                        new
                        {
                            ConnectedPumpsId = 36,
                            ConnectedTanksId = 25
                        },
                        new
                        {
                            ConnectedPumpsId = 36,
                            ConnectedTanksId = 26
                        },
                        new
                        {
                            ConnectedPumpsId = 36,
                            ConnectedTanksId = 27
                        },
                        new
                        {
                            ConnectedPumpsId = 37,
                            ConnectedTanksId = 28
                        },
                        new
                        {
                            ConnectedPumpsId = 37,
                            ConnectedTanksId = 29
                        },
                        new
                        {
                            ConnectedPumpsId = 37,
                            ConnectedTanksId = 30
                        },
                        new
                        {
                            ConnectedPumpsId = 37,
                            ConnectedTanksId = 31
                        },
                        new
                        {
                            ConnectedPumpsId = 38,
                            ConnectedTanksId = 28
                        },
                        new
                        {
                            ConnectedPumpsId = 38,
                            ConnectedTanksId = 29
                        },
                        new
                        {
                            ConnectedPumpsId = 38,
                            ConnectedTanksId = 30
                        },
                        new
                        {
                            ConnectedPumpsId = 38,
                            ConnectedTanksId = 31
                        },
                        new
                        {
                            ConnectedPumpsId = 39,
                            ConnectedTanksId = 28
                        },
                        new
                        {
                            ConnectedPumpsId = 39,
                            ConnectedTanksId = 29
                        },
                        new
                        {
                            ConnectedPumpsId = 39,
                            ConnectedTanksId = 30
                        },
                        new
                        {
                            ConnectedPumpsId = 39,
                            ConnectedTanksId = 31
                        },
                        new
                        {
                            ConnectedPumpsId = 40,
                            ConnectedTanksId = 28
                        },
                        new
                        {
                            ConnectedPumpsId = 40,
                            ConnectedTanksId = 29
                        },
                        new
                        {
                            ConnectedPumpsId = 40,
                            ConnectedTanksId = 30
                        },
                        new
                        {
                            ConnectedPumpsId = 40,
                            ConnectedTanksId = 31
                        },
                        new
                        {
                            ConnectedPumpsId = 41,
                            ConnectedTanksId = 32
                        },
                        new
                        {
                            ConnectedPumpsId = 41,
                            ConnectedTanksId = 33
                        },
                        new
                        {
                            ConnectedPumpsId = 42,
                            ConnectedTanksId = 32
                        },
                        new
                        {
                            ConnectedPumpsId = 42,
                            ConnectedTanksId = 33
                        },
                        new
                        {
                            ConnectedPumpsId = 43,
                            ConnectedTanksId = 32
                        },
                        new
                        {
                            ConnectedPumpsId = 43,
                            ConnectedTanksId = 33
                        },
                        new
                        {
                            ConnectedPumpsId = 44,
                            ConnectedTanksId = 32
                        },
                        new
                        {
                            ConnectedPumpsId = 44,
                            ConnectedTanksId = 33
                        });
                });

            modelBuilder.Entity("gsst.Model.BonusCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BonusBalance")
                        .HasColumnType("REAL");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BonusCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1234",
                            BonusBalance = 100.0,
                            ClientName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "5678",
                            BonusBalance = 200.0,
                            ClientName = "Jane Smith"
                        });
                });

            modelBuilder.Entity("gsst.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "A-95",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "A-92",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Diesel",
                            Price = 6.0
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Gas",
                            Price = 3.0
                        });
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GasStationId");

                    b.ToTable("Pumps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GasStationId = 1,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            GasStationId = 1,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            GasStationId = 2,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            GasStationId = 2,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            GasStationId = 3,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            GasStationId = 3,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            GasStationId = 3,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            GasStationId = 3,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            GasStationId = 4,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            GasStationId = 4,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            GasStationId = 4,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            GasStationId = 4,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            GasStationId = 5,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            GasStationId = 5,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            GasStationId = 5,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            GasStationId = 5,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            GasStationId = 6,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            GasStationId = 6,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            GasStationId = 6,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            GasStationId = 6,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            GasStationId = 7,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            GasStationId = 7,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            GasStationId = 7,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            GasStationId = 7,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            GasStationId = 8,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            GasStationId = 8,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            GasStationId = 8,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            GasStationId = 8,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            GasStationId = 9,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            GasStationId = 9,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            GasStationId = 9,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            GasStationId = 9,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            GasStationId = 10,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            GasStationId = 10,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            GasStationId = 10,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            GasStationId = 10,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            GasStationId = 11,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            GasStationId = 11,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            GasStationId = 11,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            GasStationId = 11,
                            Name = "Pump 4",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            GasStationId = 12,
                            Name = "Pump 1",
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            GasStationId = 12,
                            Name = "Pump 2",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            GasStationId = 12,
                            Name = "Pump 3",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            GasStationId = 12,
                            Name = "Pump 4",
                            Status = 0
                        });
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GasStationId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 1,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 1,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 2,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 2,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 3,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 3,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 3,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 3,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 4,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 4,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 5,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 5,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 5,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 6,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 6,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 6,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 6,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 7,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 7,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 8,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 9,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 9,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 9,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 9,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 10,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 10,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 10,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 11,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 11,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 10000.0,
                            FuelTypeId = 3,
                            GasStationId = 11,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 10000.0,
                            FuelTypeId = 4,
                            GasStationId = 11,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 10000.0,
                            FuelTypeId = 1,
                            GasStationId = 12,
                            Volume = 5000.0
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 10000.0,
                            FuelTypeId = 2,
                            GasStationId = 12,
                            Volume = 5000.0
                        });
                });

            modelBuilder.Entity("gsst.Model.GasStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GasStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Złota 59, 00-120 Warszawa",
                            Latitude = 52.229999999999997,
                            Longitude = 21.002400000000002,
                            Name = "Shell Warszawa Centrum"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Targowa 12, 03-736 Warszawa",
                            Latitude = 52.251399999999997,
                            Longitude = 21.041599999999999,
                            Name = "Shell Warszawa Praga"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Wolska 15, 01-201 Warszawa",
                            Latitude = 52.233499999999999,
                            Longitude = 20.970199999999998,
                            Name = "Orlen Warszawa Wola"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Puławska 427, 02-801 Warszawa",
                            Latitude = 52.148099999999999,
                            Longitude = 21.020499999999998,
                            Name = "BP Warszawa Mokotów"
                        },
                        new
                        {
                            Id = 5,
                            Address = "KEN 98, 02-777 Warszawa",
                            Latitude = 52.152799999999999,
                            Longitude = 21.045000000000002,
                            Name = "Circle K Warszawa Ursynów"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kasprowicza 117, 01-949 Warszawa",
                            Latitude = 52.285899999999998,
                            Longitude = 20.938800000000001,
                            Name = "Lotos Warszawa Bielany"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Grójecka 100, 02-389 Warszawa",
                            Latitude = 52.2104,
                            Longitude = 20.975000000000001,
                            Name = "Shell Warszawa Ochota"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Mickiewicza 20, 01-517 Warszawa",
                            Latitude = 52.2682,
                            Longitude = 20.985600000000002,
                            Name = "Orlen Warszawa Żoliborz"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Radzyminska 200, 03-674 Warszawa",
                            Latitude = 52.274099999999997,
                            Longitude = 21.074300000000001,
                            Name = "Amic Warszawa Targówek"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Patriotów 100, 04-944 Warszawa",
                            Latitude = 52.180199999999999,
                            Longitude = 21.189499999999999,
                            Name = "Moya Warszawa Wawer"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Krakowska 200, 02-219 Warszawa",
                            Latitude = 52.183399999999999,
                            Longitude = 20.941600000000001,
                            Name = "Circle K Warszawa Włochy"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Górczewska 212, 01-460 Warszawa",
                            Latitude = 52.2393,
                            Longitude = 20.916499999999999,
                            Name = "BP Warszawa Bemowo"
                        });
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccruedBonuses")
                        .HasColumnType("REAL");

                    b.Property<int?>("BonusCardId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BonusSpent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PumpId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("gsst.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("gsst.Model.User.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("gsst.Model.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GasStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GasStationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Михайло Стадніков",
                            Password = "admin",
                            PhoneNumber = "+48000000001",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Олексій Романенко",
                            Password = "cashier",
                            Role = "Cashier",
                            Username = "cashier"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Manager Station 1",
                            GasStationId = 1,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager1"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Manager Station 2",
                            GasStationId = 2,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager2"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Manager Station 3",
                            GasStationId = 3,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager3"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Manager Station 4",
                            GasStationId = 4,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager4"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Manager Station 5",
                            GasStationId = 5,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager5"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Manager Station 6",
                            GasStationId = 6,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager6"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Manager Station 7",
                            GasStationId = 7,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager7"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Manager Station 8",
                            GasStationId = 8,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager8"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Manager Station 9",
                            GasStationId = 9,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager9"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Manager Station 10",
                            GasStationId = 10,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager10"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Manager Station 11",
                            GasStationId = 11,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager11"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Manager Station 12",
                            GasStationId = 12,
                            Password = "manager",
                            Role = "Manager",
                            Username = "manager12"
                        });
                });

            modelBuilder.Entity("gsst.Model.Fuel", b =>
                {
                    b.HasBaseType("gsst.Model.Product");

                    b.Property<int>("PumpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("PumpId");

                    b.HasIndex("TypeId");

                    b.HasDiscriminator().HasValue("Fuel");
                });

            modelBuilder.Entity("gsst.Model.Good", b =>
                {
                    b.HasBaseType("gsst.Model.Product");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasDiscriminator().HasValue("Good");
                });

            modelBuilder.Entity("PumpTank", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.Pump", null)
                        .WithMany()
                        .HasForeignKey("ConnectedPumpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.FuelStuff.Tank", null)
                        .WithMany()
                        .HasForeignKey("ConnectedTanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gsst.Model.BonusCard", b =>
                {
                    b.HasOne("gsst.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gsst.Model.CartItem", b =>
                {
                    b.HasOne("gsst.Model.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("gsst.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Pump", b =>
                {
                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Pumps")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gsst.Model.FuelStuff.Tank", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Tanks")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId");

                    b.HasOne("gsst.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pump");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gsst.Model.User.PaymentMethod", b =>
                {
                    b.HasOne("gsst.Model.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("gsst.Model.User.User", b =>
                {
                    b.HasOne("gsst.Model.GasStation", null)
                        .WithMany("Managers")
                        .HasForeignKey("GasStationId");
                });

            modelBuilder.Entity("gsst.Model.Fuel", b =>
                {
                    b.HasOne("gsst.Model.FuelStuff.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gsst.Model.FuelStuff.FuelType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pump");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("gsst.Model.GasStation", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Pumps");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("gsst.Model.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
